export const GET_ADDRESS_BY_ORDER_REQUEST = 'GET_ADDRESS_BY_ORDER_REQUEST';
export const GET_ADDRESS_BY_ORDER_SUCCESS = 'GET_ADDRESS_BY_ORDER_SUCCESS';
export const GET_ADDRESS_BY_ORDER_FAILURE = 'GET_ADDRESS_BY_ORDER_FAILURE';

export const GET_ADDRESS_BY_USER_REQUEST = 'GET_ADDRESS_BY_USER_REQUEST';
export const GET_ADDRESS_BY_USER_SUCCESS = 'GET_ADDRESS_BY_USER_SUCCESS';
export const GET_ADDRESS_BY_USER_FAILURE = 'GET_ADDRESS_BY_USER_FAILURE';

